version: "3.1"

services:
  db:
    container_name: "travel-quera-posgres"
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
    network_mode: host
    volumes:
      - ./query:/query
